deepavatar/deepavatar/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls', namespace="portfolio")),
    re_path(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deepavatar/portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
	path('', views.IndexView.as_view(), name="home"),
	path('contact/', views.ContactView.as_view(), name="contact"),
	path('projects/', views.ProjectsView.as_view(), name="projects"),
	path('projects/<slug:slug>', views.ProjectsDetailView.as_view(), name="projects"),
    path('get_avatar_response/', views.get_avatar_response, name='get_avatar_response'),
    path('start_avatar_chat_to_user/', views.start_avatar_chat_to_user, name='start_avatar_chat_to_user'),
    path('check_for_new_posted_video/', views.check_for_new_posted_video, name='check_for_new_posted_video'),
    path('update_avatar_feed/<str:video_path>/', views.update_avatar_feed, name='update_avatar_feed')
]

deepavatar/portfolio/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField
import uuid


class AvatarFeed(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    user_question_message = models.CharField(max_length=300, blank=True, null=True)
    video_path = models.CharField(max_length=300, blank=True, null=True)
    video_changed = models.CharField(max_length=50, blank=True, null=True)
    first_video = models.CharField(max_length=50, blank=True, null=True)


class Skill(models.Model):
    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'
    
    name = models.CharField(max_length=20, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)
    image = models.FileField(blank=True, null=True, upload_to="skills")
    is_key_skill = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'

class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Projects(models.Model):

    class Meta:
        verbose_name_plural = 'Projects Profiles'
        verbose_name = 'Projects'
        ordering = ["name"]
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="projects")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Projects, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/projects/{self.slug}"

class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

deepavatar/portfolio/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			'class': 'form-control'
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			'class': 'form-control'
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'class': 'form-control',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

deepavatar/portfolio/views.py
import os
from django.shortcuts import render
from django.contrib import messages
import pandas as pd
from .models import (
		UserProfile,
		Projects,
		Certificate,
		AvatarFeed,
		Skill
	)
from django.views import generic
from django.http import JsonResponse, StreamingHttpResponse
from .forms import ContactForm
from .utils import chat, avatar_gen, ScriptFinder, generate_presigned_url


video_paths = [
    "1.mp4",
    "2.mp4",
    "3.mp4",
    "4.mp4",
    "5.mp4",
    "6.mp4",
    "7.mp4",
    "8.mp4",
    "9.mp4",
    "10.mp4",
    "11.mp4",
    "12.mp4",
    "13.mp4",
    "14.mp4",
    "15.mp4",
    "16.mp4",
    "17.mp4",
    "18.mp4",
    "19.mp4",
    "20.mp4",
    "21.mp4",
    "22.mp4",
    "23.mp4",
    "24.mp4",
    "25.mp4",
    "26.mp4",
    "27.mp4",
    "28.mp4"
]


def start_avatar_chat_to_user(request):
	if request.method == "POST":
		the_feed = AvatarFeed()
		the_feed.user_question_message = "None"
		the_feed.video_path = "None"
		the_feed.video_changed = "False"
		the_feed.first_video = "False"
		the_feed.save()
		the_feed_object_id = str(the_feed.pk)

		response = {
			'the_feed_object_id': the_feed_object_id 
		}

		return JsonResponse(response)

def check_for_new_posted_video(request):
	if request.method == "POST":
		feed_object_id = request.POST.get("feed_object_id", None)
		
		if feed_object_id != "OFF":
			the_feed = AvatarFeed.objects.filter(pk=feed_object_id).first()
			video_changed = the_feed.video_changed
			first_video = the_feed.first_video
			# print("video_changed")
			# print(video_changed)
			# print("first_video")
			# print(first_video)

			if video_changed == "True":
				new_video = "True"
				video_path = the_feed.video_path
				the_feed.video_changed = "False"
				the_feed.save(update_fields=["video_changed"])
				video_path = generate_presigned_url(video_path)
			else:
				new_video = "False"
				video_path = "None"
		else:
			new_video = "False"
			first_video = "False"
			video_path = "None"

		response = {
			'new_video': new_video,
			'first_video': first_video,
			'video_path': video_path,
		}

		return JsonResponse(response)

def get_avatar_response(request):
	if request.method == "POST":
		user_question_text = request.POST.get("user_question_text", None)
		feed_object_id = request.POST.get("feed_object_id", None)
		started_asking_questions = request.POST.get("started_asking_questions", None)

		the_feed = AvatarFeed.objects.filter(pk=feed_object_id).first()
		the_feed_object_id = feed_object_id
		curr_user_question_message = the_feed.user_question_message
		the_feed.user_question_message = user_question_text
		the_feed.save(update_fields=["user_question_message"])

		# First Question!
		#scripts_path = os.path.join(os.getcwd(), "Scripts.xlsx")
		scripts_path = "/mnt/avatar_storage/Scripts.xlsx"
		embedded_scripts_path = "/mnt/avatar_storage/Scripts_embedding.csv"
		script_finder = ScriptFinder(embedded_scripts_path)

		#script_finder.generate_embeddings_from_scripts()
		
		the_feed = AvatarFeed.objects.filter(pk=the_feed_object_id).first()
		new_user_question_message = the_feed.user_question_message

		# if new_user_question_message != curr_user_question_message:
		# 	curr_user_question_message = new_user_question_message

		# 	video_path = video_paths[new_user_question_message]
			
		# 	the_feed.video_path = video_path
		# 	the_feed.video_changed = "True"
		# 	the_feed.first_video = "False"
		# 	the_feed.save(update_fields=["video_path", "video_changed", "first_video"])
		# elif first_question == True:
		# 	first_question = False

		# 	video_path = video_paths[new_user_question_message]
			
		# 	the_feed.video_path = video_path
		# 	the_feed.video_changed = "True"
		# 	the_feed.first_video = "True"
		# 	the_feed.save(update_fields=["video_path", "video_changed", "first_video"])

		if new_user_question_message != curr_user_question_message:
			curr_user_question_message = new_user_question_message
			model_response = chat(curr_user_question_message)

			# script_finder.df = pd.read_csv(embedded_scripts_path)
			
			query_results = script_finder.find_similar_text(model_response)
			video_path = query_results.iloc[0]["video_path"]
			the_feed.video_path = video_path
			the_feed.video_changed = "True"
			the_feed.first_video = "False"
			the_feed.save(update_fields=["video_path", "video_changed", "first_video"])
		# elif first_question == True:
		# 	first_question = False
		# 	model_response = chat(curr_user_question_message)
			
		# 	query_results = script_finder.find_similar_text(model_response)
		# 	video_path = query_results.iloc[0]["video_path"]
		# 	the_feed.video_path = video_path
		# 	the_feed.video_changed = "True"
		# 	the_feed.first_video = "True"
		# 	the_feed.save(update_fields=["video_path", "video_changed", "first_video"])
		
		response = {
			'msg': "success"
		}

		return JsonResponse(response)

		# if started_asking_questions == "False":
		# 	# First Question!
		# 	#scripts_path = os.path.join(os.getcwd(), "Scripts.xlsx")
		# 	scripts_path = "/mnt/avatar_storage/Scripts.xlsx"
		# 	script_finder = ScriptFinder(scripts_path)
		# 	script_finder.generate_embeddings_from_scripts()

		# 	curr_user_question_message = user_question_text
		# 	first_question = True

		# 	while(True):
		# 		the_feed = AvatarFeed.objects.filter(pk=the_feed_object_id).first()
		# 		new_user_question_message = the_feed.user_question_message

		# 		# if new_user_question_message != curr_user_question_message:
		# 		# 	curr_user_question_message = new_user_question_message

		# 		# 	video_path = video_paths[new_user_question_message]
					
		# 		# 	the_feed.video_path = video_path
		# 		# 	the_feed.video_changed = "True"
		# 		# 	the_feed.first_video = "False"
		# 		# 	the_feed.save(update_fields=["video_path", "video_changed", "first_video"])
		# 		# elif first_question == True:
		# 		# 	first_question = False

		# 		# 	video_path = video_paths[new_user_question_message]
					
		# 		# 	the_feed.video_path = video_path
		# 		# 	the_feed.video_changed = "True"
		# 		# 	the_feed.first_video = "True"
		# 		# 	the_feed.save(update_fields=["video_path", "video_changed", "first_video"])

		# 		if new_user_question_message != curr_user_question_message:
		# 			curr_user_question_message = new_user_question_message
		# 			model_response = chat(curr_user_question_message)
					
		# 			query_results = script_finder.find_similar_text(model_response)
		# 			video_path = query_results.iloc[0]["video_path"]
		# 			the_feed.video_path = video_path
		# 			the_feed.video_changed = "True"
		# 			the_feed.first_video = "False"
		# 			the_feed.save(update_fields=["video_path", "video_changed", "first_video"])
		# 		elif first_question == True:
		# 			first_question = False
		# 			model_response = chat(curr_user_question_message)
					
		# 			query_results = script_finder.find_similar_text(model_response)
		# 			video_path = query_results.iloc[0]["video_path"]
		# 			the_feed.video_path = video_path
		# 			the_feed.video_changed = "True"
		# 			the_feed.first_video = "True"
		# 			the_feed.save(update_fields=["video_path", "video_changed", "first_video"])
		
		# response = {
		# 	'msg': "success"
		# }

		# return JsonResponse(response)

def update_avatar_feed(request, video_path=""):
	return StreamingHttpResponse(avatar_gen(video_path), content_type='multipart/x-mixed-replace; boundary=frame')

class IndexView(generic.TemplateView):
	template_name = "portfolio/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		certificates = Certificate.objects.filter(is_active=True)
		projects = Projects.objects.filter(is_active=True)
		skills = Skill.objects.all()
		
		context["certificates"] = certificates
		context["projects"] = projects
		context["skills"] = skills
		return context

class ContactView(generic.FormView):
	template_name = "portfolio/contact.html"
	form_class = ContactForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form)

class ProjectsView(generic.ListView):
	model = Projects
	template_name = "portfolio/projects.html"
	paginate_by = 10

	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)

class ProjectsDetailView(generic.DetailView):
	model = Projects
	template_name = "portfolio/projects-detail.html"

deepavatar/portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{%endblock %}</title>
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'portfolio:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/coffee_logo_small.jpg' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/coffee_logo_small.jpg' %}">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block extend_header%}{%endblock%}

  </head>
  <body>
    {% include 'portfolio/partials/messages.html' %}
    {% include 'portfolio/partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'portfolio/partials/footer.html' %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extra_js %}{%endblock%}
    {% block extend_footer %}{%endblock%}
  </body>
</html>

deepavatar/portfolio/templates/portfolio/contact.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}

{% block extend_header %}{% endblock %}

{% block extend_footer %}{% endblock %}

{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Contact me below</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
        <form id="contactForm" method="POST" action="/contact/">
        {% csrf_token %}
            <label for="name">Name</label>
            {{form.name}}

            <label for="email">Email</label>
            {{form.email}}

            <label for="subject">Message</label>
            {{form.message}}

            <input class='btn btnPrimary' type="submit" value="Submit">
        </form>
    </div>
  </div>
</section>
{%endblock%}
    

deepavatar/portfolio/templates/portfolio/index.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}

{% block extend_header %}{% endblock %}

{% block extend_footer %}{% endblock %}

{% block content %}
<div class="row">
<section>
  <div class="bannerSection">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md">
          <div class="bannerContent">
            <h1 class="xlTitle pb-3">Hi, I’m {{me.first_name|title}} {{me.last_name|title}}. <br> A {{me.userprofile.title}} </br></h1>
            <p>{{me.userprofile.bio}}</p>
            <div class="bannerBtnCol">
              <div class="row">
                <div class="col-auto">
                  <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Resume</a>
                </div>
                <div class="col-auto">
                  <a href="{% url 'portfolio:contact' %}" class="btn btnOutline">Contact</a>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-auto">
                  <button type="button" class="btn btnOutline" id="start_avatar_chat">Start Chat</button>
                </div> 
                <div class="col-auto">
                  <button type="button" class="btn btnOutline" id="user_question_submit" style="display:none" >Ask Me!</button>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <textarea id="user_question_text" rows="2" cols="200" style="display:none; width: 500px;" placeholder="Ask me a question about myself... powered by OpenAI"></textarea>
                </div>
              </div>
              <div class="row">
                <div class="col-auto">
                  <img id="my_avatar_loading_gif" src="{% static 'images/loading.gif' %}" style="display:none; width: 40px;">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md">
          <div class="row">
            <video id="my_avatar_video" width="300px" style="display: none;" autoplay muted playsinline src=""></video>
            <img id="my_avatar_waiting" width="300px" src="{% static 'images/waiting.png' %}">
            <!-- <div class="bannerUserImg"> -->
              <!-- <img id="my_avatar" src="{% static 'images/waiting.gif' %}" class="img-fluid" alt="{{me.first_name|title}} {{me.last_name|title}} avatar"> -->
              <!-- <video id="my_avatar_video" class="video" preload="auto" width="640" height="265" src="{% static 'images/waiting.gif' %}"></video> -->
              <!-- <video id="my_avatar_video" class="video" preload="auto" width="640" height="265" src="s3://avatar-digital-twin-bucket/pumpkins.mp4"></video> -->
              <!-- <video id="my_avatar_video" width="300px" preload="metadata" controls poster="{% static 'images/waiting.png' %}" autoplay muted playsinline src=""></video> -->
              
              <!-- <center><div class="btn-group" style="width: 500px;">
                
                
              </div></center>
               -->
            <!-- </div> -->
          </div>
          <input type="hidden" id="feed_object_id" value="OFF" style="display:none" />
          <input type="hidden" id="started_asking_questions" value="False" style="display:none" />
        </div>
      </div>
    </div>
  </div>
</section>
</div>
<div class="row">
<section>
  <div class="sectionSpace pt-0">
    <div class="container">
      <div class="row">
        <!-- <div class="col-md-auto">
          <div class="keySkillCol">
            <h4 class="smTitle pb-3">Key Skills</h4>
            {% for sk in skills %}
            {% if sk.is_key_skill %}
            <div class="keySkillCard">
              {% if sk.image %}
              <div class="ksIconCol">
                <img src="{{sk.image.url}}" alt="...">
              </div>
              {% endif %}
              <span class="ksText">{{sk.name}}</span>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div> -->
        <div class="col-md">
          <h4 class="smTitle pb-3">Coding Skills</h4>
          <div class="progressCol">
            <div class="progressCard" style="overflow-y: auto; overflow-x: hidden; max-height: 500px;">
              {% for sk in skills %}
              {% if sk.is_key_skill %}
              <div class="progressCol">
                <span class="progressLbl">{{sk.name}}</span>
                <div class="row g-2 align-items-center">
                  <div class="col">
                    <div class="progress progressStyle">
                      <div class="progress-bar" role="progressbar" style="width: {{sk.score}}%" aria-valuenow="{{sk.score}}" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                  <div class="col-auto">
                    <span class="pLbl">{{sk.score}}%</span>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div>
<div class="row">
<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Qualifications & Awards</h4>
        </div>

      </div>
      <div class="sliderOuter">
        <div class="swiper certificatesSlider">
          <div class="swiper-wrapper">
            {% for c in certificates %}
            {% if c.is_active %}
            <div class="swiper-slide">
              <div class="cardStyle1">
                <h4 class="mdTitle cs1Title">
                  <a href="javascript:void(0)">{{c.title}}</a>
                </h4>
                <ul class="cardOptionCol">
                  <li>{{c.date.date}}</li>
                  <li>{{c.name|title}}</li>
                </ul>
                <p>{{c.description}}</p>
              </div>
            </div>
            {% endif %}
            {% endfor %}
            
          </div>
        </div>            
        <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
        <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
        <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
      </div>
    </div>
  </div>
</section>
</div>
<div class="row">
<section>
  <div class="sectionSpace">
    <div class="container">
      <div class="projectsCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Featured Work</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'portfolio:projects' %}" class="simpleLink">View all</a>
          </div>
        </div>
        {% for p in projects %}
        {% if p.is_active %}
        <div class="projectsCard">
          <div class="row g-4 align-items-center">
            <div class="col-md-auto">
              <div class="projectsImgCol">
                <a href="{% url 'portfolio:projects' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
              </div>
            </div>
            <div class="col-md">
              <div class="projectsContentCol">
                <h4 class="lgTitle"><a href="{% url 'portfolio:projects' slug=p.slug %}">{{p.name}}</a></h4>
                <ul class="projectsOption">
                  <li><span class="dateLbl">{{p.date.year}}</span></li>
                </ul>
                <p>{{p.description}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        
      </div>
    </div>
  </div>
</section>
</div>

{% endblock %}
{% block extra_js %}
<script>
  $("#start_avatar_chat").click(function(){
    const video = document.getElementById('my_avatar_video');
    video.muted = !video.muted
    $.ajaxSetup({headers: { "X-CSRFToken": '{{csrf_token}}' }});
    $.ajax({
      type: "POST",
      url: "{% url 'portfolio:start_avatar_chat_to_user' %}",
      data: {
        csrfmiddlewaretoken: '{{ csrf_token }}',
        dataType: "json"
      },
      success: function(msg_avatar_chat) {
        const object_id = msg_avatar_chat.the_feed_object_id;
        $("#feed_object_id").val(object_id);
        $("#started_asking_questions").val("False");
        $('#user_question_text').show();
        $('#user_question_submit').show();
        $('#start_avatar_chat').prop('disabled', true);
        // check_for_new_video_recurring(object_id);
      },
      failure: function() {
      }
    })
  });

  function check_for_new_video(object_id) {
    // console.log("Checking for new video");
    $.ajaxSetup({headers: { "X-CSRFToken": '{{csrf_token}}' }});
    $.ajax({
      type: "POST",
      url: "{% url 'portfolio:check_for_new_posted_video' %}",
      data: {
        feed_object_id: $('#feed_object_id').val(),
        csrfmiddlewaretoken: '{{ csrf_token }}',
        dataType: "json"
      },
      success: function(msg_check_new_video) {
        if (msg_check_new_video.new_video == "True") {
          $('#my_avatar_loading_gif').hide();
          
          update_avatar(msg_check_new_video);
        }   
      },
      failure: function() {
      }
    })
    
    // setTimeout(check_for_new_video(object_id), 10000);
  };

  function check_for_new_video_recurring(object_id) {
    // check_for_new_video(object_id);
    const intervalId = setInterval(check_for_new_video, 1000, object_id);
    // setInterval(check_for_new_video(object_id), 1000);
  };

  check_for_new_video_recurring("None");

  $("#user_question_submit").click(function(){
    $('#my_avatar_loading_gif').show();
    $.ajaxSetup({headers: { "X-CSRFToken": '{{csrf_token}}' }});
    $.ajax({
      type: "POST",
      url: "{% url 'portfolio:get_avatar_response' %}",
      data: {
        user_question_text: $('#user_question_text').val(),
        started_asking_questions: $('#started_asking_questions').val(),
        feed_object_id: $('#feed_object_id').val(),
        csrfmiddlewaretoken: '{{ csrf_token }}',
        dataType: "json"
      },
      success: function(msg) {
      },
      failure: function() {
      }
    })
  });
</script>
<script>
  function update_avatar(msg_data) {
    const video_path = msg_data.video_path;
    $('#my_avatar_waiting').hide();
    
    // const the_url = ["/portfolio/update_avatar_feed/", video_number].join('');
    $('#my_avatar_video').attr("src", video_path);
    $('#my_avatar_video').show();
  };
</script>
<script>
  // var video = document.querySelector('my_avatar_video');       
  // video.addEventListener('ended', function() {
  //   video.load();     
  // });
  const video = document.getElementById('my_avatar_video');

  video.addEventListener('ended', function () { 
    // $('#my_avatar_video').attr("src", "");
    $('#my_avatar_video').hide();
    $('#my_avatar_waiting').show();
    // video.autoplay=false; 
    // video.load(); 
  });

  // function myHandler(e) {
  //   //const video_waiting_gif = "{% static 'images/waiting.gif' %}"
  //   $('#my_avatar_video')[0].load();
  // }
</script>
{%endblock%}